name: Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # استفاده از اکشن رسمی و بروز شده برای بیلد خودکار بدون نیاز به نصب دستی ابزارها
    - name: Build APK with Buildozer Action
      uses: Actionman444/buildozer-action@v1.2
      with:
        buildozer_version: 'stable'
        command: buildozer android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SpeedCar-APK
        path: bin/*.apk
